openapi: 3.0.0
info:
  title: Simple Note-Taking API
  description: A RESTful API for managing notes.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local server

paths:
  /notes:
    post:
      summary: Create a new note
      description: Allows API consumers to create a new note with a title and body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Sample Note"
                body:
                  type: string
                  example: "This is the content of the note."
      responses:
        '201':
          description: Note created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '500':
          description: Server error

    get:
      summary: Get all notes
      description: Retrieves a list of all notes.
      responses:
        '200':
          description: A list of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
        '500':
          description: Server error

  /notes/{id}:
    get:
      summary: Fetch a note by ID
      description: Retrieves a note using its primary key (ID).
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the note to retrieve
      responses:
        '200':
          description: Note retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
        '500':
          description: Server error

    put:
      summary: Update a note
      description: Updates the title and body of an existing note identified by its primary key.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the note to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Updated Note Title"
                body:
                  type: string
                  example: "Updated content of the note."
      responses:
        '200':
          description: Note updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
        '500':
          description: Server error

  /notes:
    get:
      summary: Query notes by title substring
      description: Retrieves notes that contain a specific substring in their title.
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
          description: The substring to search for in the title
      responses:
        '200':
          description: A list of notes matching the query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
        '500':
          description: Server error

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the note
          example: "61234abcde1234f567890123"
        title:
          type: string
          description: The title of the note
          example: "Sample Note"
        body:
          type: string
          description: The main content of the note
          example: "This is the content of the note."
        created_at:
          type: string
          format: date-time
          description: The date and time the note was created
          example: "2024-08-12T12:34:56Z"
        updated_at:
          type: string
          format: date-time
          description: The date and time the note was last updated
          example: "2024-08-12T12:34:56Z"
